#ifndef __AVS3_ENUM_H__
#define __AVS3_ENUM_H__


enum AVS_Error_Code_
{
  AVS_ERROR_BAD_DIMENSION,
  AVS_ERROR_BROKEN_FILE,
  AVS_ERROR_COLLISION_COLORSPACE,
  AVS_ERROR_COLLISION_DIMENSION,
  AVS_ERROR_COLLISION_FPS,
  AVS_ERROR_COLLISION_FRAMECOUNT,
  AVS_ERROR_COLORPSACE_INVALID_HEIGHT,
  AVS_ERROR_COLORPSACE_INVALID_WIDTH,
  AVS_ERROR_COLORPSACE_UNKNOWN,
  AVS_ERROR_COLORPSACE_UNSUPPORTED,
  AVS_ERROR_FATAL,
  AVS_ERROR_GENERIC,
  AVS_ERROR_GSTREAMER,
  AVS_ERROR_NO_AUDIO,
  AVS_ERROR_NO_SUCH_FILE,
  AVS_ERROR_NO_SUCH_FRAME,
  AVS_ERROR_NO_SUCH_PLANE,
  AVS_ERROR_NO_VIDEO
};

typedef enum AVS_Error_Code_ AVS_Error_Code;

#endif /* __AVS3_ENUM_H__ */
